/* 
    This is the code to generate ajv_v3.json, the stage III datasource schema validation
    requires: mongoose
              ajv2.json generated by mongooseTest2.js
    Purposes
            - check all the patient IDs
*/
var jsonfile = require("jsonfile");
var ajvMsg = [];
var Ajv = require('ajv');
var ajv = new Ajv({allErrors: true});
var asyncLoop = require('node-async-loop');
var db;
const mongoose = require("mongoose");
var dataTypes_ptIDsAsNestedValues = ['color', 'edges'];
var dataTypes_ptIDsAsValues = ['patient', 'drug', 'newTumor', 'otherMalignancy-v4p0', 'radiation', 'followUp-v1p0',
                               'followUp-v1p5', 'followUp-v2p1', 'followUp-v4p0', 'followUp-v4p8', 'followUp-v4p4',
                               'newTumor-followUp-v4p0', 'newTumor-followUp-v4p8', 'newTumor-followUp-v4p4'];
var dataTypes_ptIDsAsKeys = ['mut', 'mut01', 'events', 'methylation', 'rna', 'protein', 'psi', 'facs', 'cnv', 'pcaScores',
                             'pcaLoadings', 'mds', 'ptDegree', 'geneDegree'];

jsonfile.readFile("ajv_2.json", function(err, obj) {
  ajvMsg = obj;
});

mongoose.connect(
    'mongodb://oncoscape-dev-db1.sttrcancer.io:27017,oncoscape-dev-db2.sttrcancer.io:27017,oncoscape-dev-db3.sttrcancer.io:27017/pancan12?authSource=admin', {
        db: {
            native_parser: true
        },
        server: {
            poolSize: 5,
            reconnectTries: Number.MAX_VALUE
        },
        replset: {
            rs_name: 'rs0'
        },
        user: 'oncoscapeRead',
        pass: 'i1f4d9botHD4xnZ'
    });

var connection = mongoose.connection;
var col_count = 0;
connection.once('open', function(){
    var db = connection.db; 
    asyncLoop(dataType, function(t, next){  
        console.log("Within datatype: ", t);
        var categoried_collections = collections.findCollectionsByType(t); 
        var categoried_collection_length = categoried_collections.length; 
        var category_index = 0;

        var drug = connection.db.collection("brca_drug_tcga_clinial").find({},{'patient_ID':true});
        drug.each(function(err, item){
              if(item != null){
                console.log(item);
              }
              console.log(err);
        });
        /*
        */

    }, function (err)
    {
        if (err)
        {
            console.error('Error: ' + err.message);
            return;
        }
     
        console.log('Finished!');
    });

});




ajvMsg_v3 = ajvMsg.map(function(a){
    var elem = {};
    elem.collection = a.collection;
    elem.type = a.type;
    elem.disease = a.disease;
    elem.passedCounts = a.passedCounts;
    elem.totalCounts = a.totalCounts;
    elem.passedRate = a.passedCounts/a.totalCounts;
    elem.errorMessage = a.errors.table(a.nestedUnique());
    return elem;
});

jsonfile.writeFile('ajv_v2.json', ajvMsg_v2, {spaces:4}, function(err){console.log(err);});
