/* 
    This is the code to generate report_arr.json, tool-based validation
    requires: mongoose
              ajv_tcga_v2_10182016.json generated by mongooseTest2.js
              ptList.json generated by generatePatientListForDisease.js
              schemas.json manualy generated
    Purposes
            - validate the tool accessible according to the collection existence
            - incorperate the datasource quality data into tool validation

*/

var jsonfile = require("jsonfile-promised");
var u = require("underscore");
var test = {
  "pca" : require("./moduleTesting/test_pca.js"),
  "spreadsheet" : require("./moduleTesting/test_Spreadsheet.js"),
  "timelines" : require("./moduleTesting/test_Timelines.js"),
  "clusters" : require("./moduleTesting/test_Clusters.js"),
  "heatmap" : require("./moduleTesting/test_Heatmap.js"),
  "sunburst" : require("./moduleTesting/test_Sunburst.js")
}

var Ajv = require('ajv');
var ajv = new Ajv({allErrors: true});
const schemas = require("../schemas.json");
const ptList = require("./ptList.json");
const ajvMsg = require("../datasourceTesting/ajv_tcga_v2_10182016.json");
var collection;
var all_collections = [];
const mongoose = require("mongoose");
var lookupByDisease = [];
var lookupByTool = [];
var disease_arr = [];
var render_pca_diseases;
var render_chr;
var render_chr_arr = [];
var render_pt;
var render_pt_arr = [];
var diseaseCollectionSchema = {
    "properties": {
        "disease": {"type": "string"}, 
        "source" : {"type": "string", "default": "TCGA"}, 
        "beta" : {"type": ["boolean", "string"]}, 
        "img" : {"type": "string"}, 
        "category": {"type": "array", 
                     "items": {"type": "object", 
                               "properties": {
                                  "source": {"type": "string"}, 
                                  "type": {"type": "string"}, 
                                  "collection": {"type": "string"}
                               },
                                "required": ["source", "type", "collection"]
                             }
                    },
        "molecular": {"type": "array", 
                     "items": {"type": "object", 
                               "properties": {
                                  "source": {"type": "string"}, 
                                  "type": {"type": "string"}, 
                                  "collection": {"type": "string"}
                               },
                                "required": ["source", "type", "collection"]
                             }
                    },
        "calculated": {"type": "array", 
                     "items": {"type": "object", 
                               "properties": {
                                  "source": {"type": "string"}, 
                                  "type": {"type": "string"}, 
                                  "collection": {"type": "string"}
                                },
                                "required": ["source", "type", "collection"]
                             }
                    },
        "clinical": {
                    "properties":{
                       "events": {"type": "string"},
                       "patient": {"type": "string"},
                       "drug": {"type": "string"},
                       "radiation": {"type": "string"},
                       "newTumor": {"type": "string"},
                       "otherMalignancy": {"type": "string"} 
                    },
                    "required": ["events", "patient", "drug", "radiation", "newTumor", "otherMalignancy"],
                    "additionalProperties": true
                    },
         "edges": {"type": "array", 
                     "items": {"type": "object", 
                               "properties": {
                                  "name": {"type": "string"}, 
                                  "source": {"type": "string"}, 
                                  "edges": {"type": "string"},
                                  "patientWeights": {"type": "string"},
                                  "genesWeights": {"type": "string"}
                               },
                                "required": ["name", "source", "edges", "patientWeights", "genesWeights"]
                             }
                    }                                    

    }
    ,
    "required": ["_id", "source", "beta", "name", "molecular", "calculated",  "clinical", "edges"], 
    "additionalProperties": true

};


Array.prototype.findCollectionsByDisease = function(d){
  var arr = [];
  for(var i = 0; i < this.length; i++) {
    if(this[i].disease === d){
      arr.push(this[i]);
    } 
  }
  return arr;
};

Array.prototype.unique = function() {
  var arr = [];
  for(var i = 0; i < this.length; i++) {
      if(arr.indexOf(this[i]) === -1) {
          arr.push(this[i]);
      }
  }
  return arr; 
};

Array.prototype.findScoreByDiseaseByType = function(t, d) {
  var passedRateArray = [];
  this.forEach(function(a){
    if(a.type==t && a.disease==d) 
      passedRateArray.push(a.passedRate);
  });
  return passedRateArray;
};

Array.prototype.findScoreByType = function(t) {
  var passedRateArray = [];
  this.forEach(function(a){
    if(a.type==t) 
      passedRateArray.push(a.passedRate);
  });
  return passedRateArray;
};

Array.prototype.findScoreByDiseaseByType = function(t, d) {
  var passedRateArray = [];
  this.forEach(function(a){
    if(a.type==t && a.disease==d) 
      passedRateArray.push(a.passedRate);
  });
  return passedRateArray;
};

mongoose.connect(
    'mongodb://oncoscape-dev-db1.sttrcancer.io:27017,oncoscape-dev-db2.sttrcancer.io:27017,oncoscape-dev-db3.sttrcancer.io:27017/tcga?authSource=admin', {
        db: {
            native_parser: true
        },
        server: {
            poolSize: 5,
            reconnectTries: Number.MAX_VALUE
        },
        replset: {
            rs_name: 'rs0'
        },
        user: 'oncoscapeRead',
        pass: 'i1f4d9botHD4xnZ'
});

var connection = mongoose.connection;
var j = 0;
var report_arr = [];
var elem = {};
var diseases = [];
var tools = [];
var diseaseCollectionStructuralStatus = [];
connection.once('open', function(){

    // Testing the disease collection structure using tcga:brain as a gold standard
    // current database : pancan12

    lookupByDisease = connection.db.collection("lookup_oncoscape_datasources").find().toArray();
    lookupByDisease.then(function(obj){
      obj.forEach(function(item){
            var elem = {};
            elem.disease = item['disease'];
            elem.collectionStructural = [];
            console.log(item['disease']);
            diseases.push(item['disease']);
            disease_arr.push(item);

            //test against tcga:brain element from lookup_oncoscape_datasources
            var valid = ajv.validate(diseaseCollectionSchema, item);
            if(!valid){
              console.log(ajv.errors);
              elem.collectionStructural = ajv.errors;
          }
          diseaseCollectionStructuralStatus.push(elem); 
        });      
    }); 

    jsonfile.writeFile("diseaseCollectionStructuralStatus.json", diseaseCollectionStructuralStatus, {spaces:4});

    lookupByTool = connection.db.collection("lookup_oncoscape_tools").find().toArray().then(function(obj){
       tools = obj.map(function(o){return o.name;});   
    });

    render_chr = connection.db.collection("render_chromosome").find().toArray().then(function(obj){
        render_chr_arr = obj.map(function(o){return o.name;});
    });

    connection.db.collection("render_patient").find().toArray().then(function(obj){
      render_pt_arr = obj.map(function(o){return o.name;});
    });

    connection.db.collection("render_pca").distinct("disease").then(function(obj){render_pca_diseases = obj;});

    var general = {
      'lookupDataSource': "Exists✔️😃",
      'lookupTools': "Exists✔️😃"
    };

    connection.db.listCollections().toArray().then(function(collections){
        all_collections = collections.map(function(c){return c.name;});
     
        if(all_collections.indexOf("lookup_oncoscape_datasources") == -1){
          console.log("lookup_oncoscape_datasources DOES NOT exist❌");
          general['lookupDataSource'] = "DOES NOT exist.❌";
        }else{
          console.log("lookup_oncoscape_datasources exist✔️😃");
        }
        if(all_collections.indexOf("lookup_oncoscape_tools") == -1){
          console.log("lookup_oncoscape_tools DOES NOT exist❌");
          general['lookupTools'] = "DOES NOT exist";
        }
    });


    diseases.forEach(function(err, index){
      console.log(index);
      elem = {};
      elem['disease'] = diseases[index];
      //elem['general'] = general;
      elem['Spreadsheet'] = {};
      elem['MP'] = {};
      elem['PCA'] = {};
      elem['Clusters'] = {};
      elem['Pathways'] =  "✔️😃"; 
      elem['Timelines'] = {};
      console.log("Current dataset is: ", diseases[index]);
     
      
      if('edges' in disease_arr[index]){
        disease_arr[index]['edges'].forEach(function(err, i){
          var c =  disease_arr[index]['edges'][i];
          // console.log(c);
          if((typeof(c['edges']) == "string") && (typeof(c['patientWeights']) == "string") && (typeof(c['genesWeights']) == "string")){
            elem['MP']['edges'] = "✔️😃";
          }else{
            elem['MP']['edges'] = "❌";
          }
        });
      }else{
        elem['MP']['edges'] = "❌";
      }

      
      elem['Spreadsheet'] = test.spreadsheet.ExecTest(diseases[index], ajvMsg)? "✔️😃" : "❌";

      elem['PCA'] = test.pca.ExecTest(diseases[index], render_pca_diseases)? "✔️😃" : "❌";
      elem['Timelines'] = test.timelines.ExecTest(diseases[index], disease_arr)? "✔️😃" : "❌";
      elem['Clusters'] = test.clusters.ExecTest(diseases[index], ajvMsg)? "✔️😃" : "❌";
      elem['Heatmap'] = test.heatmap.ExecTest(diseases[index], disease_arr)? "✔️😃" : "❌";
      elem['Sunburst'] = test.sunburst.ExecTest(diseases[index], disease_arr)? "✔️😃" : "❌";   
      
      report_arr.push(elem);
    });

    jsonfile.writeFile("report_arr.json", report_arr, {spaces: 4});  
    // mongoose.connection.close();
   
});


