const u = require("underscore");
const helper = require("../testingHelper.js");
const errors = require("./CheckingMinMaxValues.json");
errors.map(function(e){return e.collection;}).unique()
// [ 'esca_mut_broad_mutsig2',
//   'gbm_mut_broad_mutsig2',
//   'brain_mut_broad_mutsig2',
//   'hnsc_mut_broad_mutsig2',
//   'kich_mut_broad_mutsig2',
//   'kirc_mut_broad_mutsig2',
//   'kirp_mut_broad_mutsig2',
//   'lgg_mut_broad_mutsig2',
//   'lihc_mut_broad_mutsig2',
//   'luad_mut_broad_mutsig2',
//   'lusc_mut_broad_mutsig2',
//   'sarc_mut_broad_mutsig2',
//   'paad_mut_broad_mutsig2',
//   'prad_mut_broad_mutsig2',
//   'skcm_mut_broad_mutsig2',
//   'stad_mut_broad_mutsig2',
//   'thca_mut_broad_mutsig2',
//   'ucec_mut_broad_mutsig2',
//   'acc_mut_broad_mutsig2',
//   'blca_mut_broad_mutsig2',
//   'brca_mut_broad_mutsig2',
//   'cesc_mut_broad_mutsig2',
//   'chol_mut_broad_mutsig2',
//   'dlbc_mut_broad_mutsig2',
//   'brca_psi_bradleylab_miso',
//   'coad_protein_ucsc_rppa',
//   'gbm_protein_ucsc_rppa',
//   'read_protein_ucsc_rppa',
//   'hnsc_protein_ucsc_rppa',
//   'lgg_protein_ucsc_rppa',
//   'luad_protein_ucsc_rppa',
//   'lusc_protein_ucsc_rppa',
//   'prad_protein_ucsc_rppa',
//   'paad_protein_ucsc_rppa',
//   'blca_protein_ucsc_rppa',
//   'stad_protein_ucsc_rppa',
//   'kirp_protein_ucsc_rppa',
//   'skcm_protein_ucsc_rppa',
//   'thca_protein_ucsc_rppa',
//   'ucec_protein_ucsc_rppa',
//   'ov_protein_ucsc_rppa',
//   'brca_protein_ucsc_rppa',
//   'sarc_methylation_ucsc_hm450' ]
