/* 
    This is the code to generate ajv_v2.json, the stage II datasource schema validation
    requires: ajv.json generated by mongooseTest.js
    Purposes
            - re-organize the error messages 
            - calculate the passed percentage at collection level
*/

const jsonfile = require("jsonfile-promised");
const helper = require("../testingHelper.js");
var ajvMsg, ajvMsg_v2;

jsonfile.readFile("ajv_tcga_11072016.json").then(function(obj){
    ajvMsg = obj;
}).then(function(){
    ajvMsg_v2 = ajvMsg.map(function(a){
        var elem = {};
        if(a!=null){
            elem.collection = a.collection;
            elem.type = a.type;
            elem.disease = a.disease;
            elem.passedCounts = a.passedCounts;
            elem.totalCounts = a.totalCounts;
            elem.passedRate = a.passedCounts/a.totalCounts;
            elem.errorMessage = helper.nestedUniqueCount(a);
        }
        
        //elem.errorMessage = a.errors.tableV2(a.nestedUnique());
        return elem;
    });
}).then(function(){
    jsonfile.writeFile('ajv_tcga_v2_11072016.json', ajvMsg_v2, {spaces:4});
});

