/* 
    This is the code to generate ajv_v2.json, the stage II datasource schema validation
    requires: ajv.json generated by mongooseTest.js
    Purposes
            - re-organize the error messages 
            - calculate the passed percentage at collection level
*/
const jsonfile = require("jsonfile-promised");
const u = require("underscore");
const helper = require("/usr/local/airflow/docker-airflow/onco-test/testingHelper.js");
var ajvMsg, ajvMsg_v2;
var ajvMsg_1 = require("/usr/local/airflow/docker-airflow/onco-test/dataStr/ajv_test2_pi1.json");
var ajvMsg_2 = require("/usr/local/airflow/docker-airflow/onco-test/dataStr/ajv_test2_pi2.json");
var ajvMsg_3 = require("/usr/local/airflow/docker-airflow/onco-test/dataStr/ajv_test2_pi3.json");
var ajvMsg_4 = require("/usr/local/airflow/docker-airflow/onco-test/dataStr/ajv_test2_pi4.json");
var ajvMsg_5 = require("/usr/local/airflow/docker-airflow/onco-test/dataStr/ajv_test2_pi5.json");
ajvMsg_v2 = ajvMsg_1.concat(ajvMsg_2, ajvMsg_3, ajvMsg_4, ajvMsg_5);
jsonfile.writeFile("/usr/local/airflow/docker-airflow/onco-test/dataStr/ajv_test2.json", ajvMsg_v2, {spaces:4}, function(err){ console.error(err);});
